# Generated by Django 3.1.4 on 2020-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
